### ISSUE TITLE
develop branch 생성의 건

### ISSUE THREAD

**Issue by chloeelog** [skojphy/fibonachicken#2]
안녕하세요 팀장님! 현재 만들어주신 레포에서 develop 브랜치를 확인할 수 없습니다.

develop 브랜치 생성 후 다시 push 해주실 수 있을까요?

이 경우 이미 fork한 레포를 삭제하고 push 이후 버전으로 다시 fork하는것이 좋을지,
혹은 folk된 레포에서 pull (혹은 fetch) 받아오는 것이 좋을지 알려주세요!

**Comment by skojphy** [comment]
지금도 혹시 브랜치 확인이 안되실까요?

**Comment by chloeelog** [comment]
확인 됩니다! 감사합니다. 

포크한 레포에 어떻게 적용하면 좋을지 알려주실 수 있을까요?
답변 주신 후 현재 이슈 클로즈해도 좋을 것 같습니다!

**Comment by skojphy** [comment]
네 다시 포크해주시면 좋을것같습니다!
